# Generated by Django 5.1.1 on 2024-09-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xác nhận'), ('preparing', 'Đang chuẩn bị hàng'), ('in_delivery', 'Đang giao hàng'), ('delivered', 'Giao thành công'), ('canceled', 'Bị hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hovaten', models.CharField(max_length=200)),
                ('sdt', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('tinh', models.CharField(max_length=255)),
                ('huyen', models.CharField(max_length=255)),
                ('diachi', models.CharField(max_length=255)),
                ('magiamgia', models.CharField(blank=True, max_length=20, null=True)),
                ('books', models.ManyToManyField(blank=True, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
