# Generated by Django 5.1.1 on 2024-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tongtien',
            field=models.IntegerField(default=0),
        ),
    ]
