# Generated by Django 5.1.1 on 2024-09-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_tracking_number_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tongtien',
            field=models.FloatField(default=0.0),
        ),
    ]
