# Generated by Django 5.1.1 on 2024-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_tongtien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Đang chuẩn bị hàng', 'Đang chuẩn bị hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Giao thành công', 'Giao thành công'), ('Bị hủy', 'Bị hủy')], default='pending', max_length=20),
        ),
    ]
