# Generated by Django 5.1.1 on 2024-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_book_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
